import Head from 'next/head';
import styles from '@/styles/Home.module.scss';
import { useState } from 'react';
import { useRouter } from 'next/router';

import json from '@/assets/data.json';

export default function Home() {
  const [ identify, setIdentify ] = useState('');

  const router = useRouter();

  const login = async() => {
    if(!Number.isNaN(Number(identify))) {
      const res = json.map((id) => {
        return id.matricula;
      }).includes(Number(identify));

      if(res == true) {
        const data = json.filter((id) => id.matricula == Number(identify));

        window.localStorage.setItem('client', JSON.stringify(data[0]));
        await router.push('/dashboard');
      } else {
        alert('Credenciais incorretas!');
      }
    } else if(/^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/.test(identify)) {
      const res = json.map((id) => {
        return id.email;
      }).includes(identify);

      if(res == true) {
        const data = json.filter((id) => id.email == identify);

        window.localStorage.setItem('client', JSON.stringify(data[0]));
        await router.push('/dashboard');
      } else {
        alert('Credenciais incorretas!');
      }
    }
  }

  return (
    <>
      <Head>
        <title>Reactions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.loginContainer}>
          <h3>ENTRAR</h3>
          <p>Faça login com seu e-mail ou número da matrícula para ver e avaliar.</p>
          <input type="text" placeholder="E-mail ou número da matrícula" value={identify.toLowerCase()} onChange={txt => setIdentify(txt.target.value.toLowerCase())} required />
          <button type="submit" onClick={login}>ENTRAR</button>
        </div>
      </main>
    </>
  )
}
